### ISSUE TITLE
Resume playback

### ISSUE THREAD

**Issue by aibaraiduas** [vanilla-music/vanilla#133]
It would be very nice if there was an option for Vanilla Music, when opened, to resume playing at the exact playback position it was at when last closed (and not simply open the last file played).

This would make it much nicer not only for very long music tracks (say, hour-long mixes), but also podcasts and audiobooks. As of now you need to remember where you left off, then manually search for that point. 

Thanks for the great music player!

**Comment by adrian-bl** [comment]
I agree that this would be a nice feature - i'll have a look at it when i have some time

**Comment by adrian-bl** [comment]
I had a look at the code and this should already work: VanillaMusic saves its seek state in onDestroy, so as long as your phone does not reboot and vanilla music gets terminated normally (eg: not forced due to a task killer), the position should be saved and restored.

**Comment by un-logic** [comment]
So, any chances for this feature to be upgraded to remember playback timestamp somewhere at nonvolatile space, e.g. with some 25s periodic timer and pause event, that triggers timestamp save to data folder or something considering more energy efficiency.
There also Material player project, they implemented required behavior. https://github.com/Ph1b/MaterialAudiobookPlayer

**Comment by adrian-bl** [comment]
Well: The code to do this is already there:
VanillaMusic stores the current queue in two ways:

#1: Every X seconds the whole queue is stored with seek-pos=0 (to restore them in case of a crash / power loss)
#2: The queue and the CURRENT SEEK POSITION is saved while Android calls onDestroy()

This is supposed to happen while Android terminates VanillaMusic to make space for some other application.

But Android does not guarantee to call onDestroy(), so it might make sense to move the save call into the 'release wakelock' function.

I'm going to target this for version 1.0.1

**Comment by adrian-bl** [comment]
I glued this (together with the audiofx session) to the release of the wakelock.
Commit https://github.com/vanilla-music/vanilla/commit/abe353b3f1ac9197d4f1450db7b95808f9bbe6cc should fix this issue.

**Comment by aibaraiduas** [comment]
I'm using 1.0.30 but this still isn't working: when VanillaMusic is closed and reopened, the last played track simply starts at the beginning again, not where it left off.

**Comment by adrian-bl** [comment]
This works just fine for me: i tested it on two devices.
Are you using some sort of task killer? Vanilla only saves the current position after 60 seconds (while entering sleep-state, eg: releasing the wake lock + closing the audiofx session)

**Comment by un-logic** [comment]
Thank you, Adrian!
Patch you have provided works just as it expected to, resume works fine to me ruining on Vanilla 1.0.30.

**Comment by aibaraiduas** [comment]
I'm not using any task killers, just closing Vanilla from the standard app switcher screen. No matter when I close it, Vanilla doesn't resume. I'm using stock Android 5.1.1 (rooted) on a Nexus 5, if that matters. My wife has the same setup, and it doesn't work for her either.

**Comment by aibaraiduas** [comment]
Actually, my wife noted that sometimes when she listens to podcasts VanillaMusic does remember where she left off (but only about a third of the time). It has never worked for me.

**Comment by adrian-bl** [comment]
Well, if you are closing Vanilla music from the app switcher, you are telling android to *kill* the process ASAP:

Removing an app from the switcher does the following:
-> It destroys any active activity
-> Calls onTaskRemoved() on the service
-> KILLS the service unless setForeground() is set (eg: is playing music)

Vanilla Music will therefore never go trough its normal shutdown process where saving the track position is implemented.

**Comment by aibaraiduas** [comment]
Ah, interesting. Maybe I'm stupid, but... how else can you close Vanilla but still have it resume playback in the proper spot? Even if I have it display a notification and close that it still does not resume. 

My original intent with filing this request was to make it so that Vanilla Music could be totally closed (even the phone restarted) but it would still resume playback.

**Comment by adrian-bl** [comment]
You just hit 'pause'. That's it.

After this, two things might happen that cause Vanilla Music to save the current track position:

* After 60 seconds, Vanilla Music will release the Wake Lock, unregister from any button receivers + save the playback position
* Android may decide that it needs more RAM and calls onDestroy(), causing a clean shutdown of the app

Removing the app from the 'recents list' doesn't start a clean shutdown - it kills the app right on the spot.

**Comment by aibaraiduas** [comment]
I see now. So yes, this actually does work fine: if I pause it for a minute it will remember its place even if I do close it with the app switcher. 

Thank you for taking the time to explain how it works!
