### ISSUE TITLE
m4a support disappeared

### ISSUE THREAD

**Issue by lukebarone** [vanilla-music/vanilla#534]
I cannot play or add .m4a files since the last update

**Comment by adrian-bl** [comment]
Which application did you use to create the M4A files?
Are they tagged?

**Comment by lukebarone** [comment]
New Pipe, selecting audio only. It seems I cannot add the songs to a
playlist, but I can manually listen to them. I don't believe the files are
tagged at all

**Comment by adrian-bl** [comment]
Newpipe is known to be broken in 1.0.48.

Its already fixed in git head and will work again in 1.0.49

**Comment by adrian-bl** [comment]
Closing this as 1.0.49 should be released soon (and the issue is already fixed in the nightly)

Thanks for your bugreport!

**Comment by lukebarone** [comment]
Downloaded 1.0.49 on OnePlus One. Still experiencing the same. Press and
hold on an .m4a file, add to playlist, "0 songs added to playlist" message.
Check the playlist, it's not there.

Not sure if it matters, but I download and manage updates through f droid

**Comment by adrian-bl** [comment]
Does the file show up in the media database or are you selecting it from the 'Files' tab?

**Comment by lukebarone** [comment]
No, they seem to only show up under Files at this time.

**Comment by lukebarone** [comment]
Scratch that. I had to manually scan every fodder to add to my media
library. The songs now show up (albeit no tagging info), and I can add to
playlists.

**Comment by adrian-bl** [comment]
Try to trigger a normal scan in the settings. If it still doesnt show up, then android missed the file and a full scan is required

**Comment by lukebarone** [comment]
It only worked after doing a full scan
