### ISSUE TITLE
Behaviour of the system "back" button when filtering by a particular genre

### ISSUE THREAD

**Issue by ecanja** [vanilla-music/vanilla#681]
- Vanilla Music Version (Settings -> About): 1.0.55
- Android Version: 5.1
- Phone vendor / model:
- Application was downloaded from:
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description

When I choose a genre in the "GENRE" tab, I get to the "ARTISTS" tab with all artists that belong to this genre. By tapping one artist, I'm getting to all albums of this artist [belonging to the chosen genre? - actually, I'm just recognizing that this seems false - I'm just getting **all** albums by this artist]. By pressing the system's back button from there, I don't get back to the list of the artists belonging to the genre (as I would expect and want to), but rather to the list of all artists in the music library.

### Rationale
From within the genre filter, I can use the system's back button to get back from titles to the previous view showing albums belonging to this artist. It would therefore just be logical to also get back from the albums of one artist to the previous view of artists belonging to the chosen genre.

For me, choosing a genre filter is like stepping one level into a tree (like a file system tree). Choosing an artist from there is another level down and the same applies for then choosing an album. The back button should just behave as if I was stepping the levels back upwards - as in a file system (and it does so for the titles view). Only when I've gotten back the entire way to the genre level, I want to see the global picture, cause only then I'm back to the initial state.

Btw: As mentioned above, I realized that the genre filter actually doesn't behave as I'd have expected: Tapping an artist after having chosen a genre, I do actually get **all** albums of that artist and not only those albums belonging to the genre. Is this intended behaviour? If not so, should I open another issue for it?

## Steps to reproduce the issue

Choose a genre, then choose an artist and from the "ALBUMS" tab press the system's back button.
_Expected result:_ I  get to the "ARTISTS" tab with the artists that belong to the album.
_Actual result:_ I get to the "ARTISTS" tab with all artists of my music library.

If I use "swipe right" instead of the back button, I do get the actual result. Therefore, I'm hereby asking for the system back button to have the same behaviour as the swipe.

**Comment by adrian-bl** [comment]
I agree that this is confusing and should be fixed:

The (internally called) limiters (= the grey labels you see at the bottom) are pretty much fake: Only the limiter on the right side displays what is filtered - all other limiters are just made up decoration:

They do not have any effect on the filtering and do not represent a 'history': They are kind of static.

Instead, the limiters really should track 'how' the user got to a filter.

**Comment by yephny** [comment]
This has been added to a past milestone but the issue still persists as far as I can tell.

1. Open an album.
2. Hit back.
3. It takes you back to albums but only the albums by the artist of the album you opened appear instead of all albums.

**Comment by xeruf** [comment]
Seconding this, going back is quite confusing

**Comment by Mikaciu** [comment]
+1
